### PR TITLE
Updated manifest.json

### PR DESCRIPTION
**Pull request by KAR2022**
Overview:
Modified image tag in manifest.json.

Connects #4 

Checklist:

manifest.json

Testing Instructions:
Pull the code from this repo.
Open the manifest.json to look for modified image tag (chop.flywheel.io/captk-whitestripe-normalization:0.0.0)

### CODE REVIEW

**Comment by afamiliar** [comment]
please update with a PR template format

**Comment by KAR2022** [comment]
> please update with a PR template format

I have updated PR with the template. Let me know if i need to add anything.

**Review by afamiliar — APPROVED** [review]
looks good

**Comment by afamiliar** [comment]
@KAR2022 I approved, feel free to merge the branch & then delete it

**Pull request merged**
